# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20171104_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmrating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Film'),
        ),
    ]
