# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='film',
            new_name='book',
        ),
    ]
