# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 04:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='images/none/blank_article.jpg', upload_to='images/articles/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='creator',
            new_name='creators',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='film_directors', to='api.Person'),
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.CharField(default='Lorem ipsum dolor sit amet,\n    consectetur adipiscing elit. Etiam maximus efficitur lacus, sit amet pretium lorem \n    iaculis id. Nulla hendrerit risus at justo imperdiet, eget sagittis felis consequat. \n    Ut tempor luctus felis id ullamcorper. Ut fringilla pharetra magna a scelerisque.\n    Maecenas nec sem varius mi rhoncus scelerisque sed sed enim. Suspendisse\n    blandit ante at ipsum feugiat, vitae ultrices enim blandit.', max_length=500),
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serial',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet,\n    consectetur adipiscing elit. Etiam maximus efficitur lacus, sit amet pretium lorem \n    iaculis id. Nulla hendrerit risus at justo imperdiet, eget sagittis felis consequat. \n    Ut tempor luctus felis id ullamcorper. Ut fringilla pharetra magna a scelerisque.\n    Maecenas nec sem varius mi rhoncus scelerisque sed sed enim. Suspendisse\n    blandit ante at ipsum feugiat, vitae ultrices enim blandit.', max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)]),
        ),
        migrations.AlterField(
            model_name='serial',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='serial_actors', through='api.Serialcast', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet,\n    consectetur adipiscing elit. Etiam maximus efficitur lacus, sit amet pretium lorem \n    iaculis id. Nulla hendrerit risus at justo imperdiet, eget sagittis felis consequat. \n    Ut tempor luctus felis id ullamcorper. Ut fringilla pharetra magna a scelerisque.\n    Maecenas nec sem varius mi rhoncus scelerisque sed sed enim. Suspendisse\n    blandit ante at ipsum feugiat, vitae ultrices enim blandit.', max_length=500),
        ),
        migrations.AlterField(
            model_name='serial',
            name='year',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)]),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.ArticleCategory'),
        ),
    ]
