# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171213_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='serial_actors', through='api.Serialcast', to='api.Person'),
        ),
    ]
