# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170929_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='images/none/', upload_to='images/'),
        ),
    ]
