# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20171217_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='images/none/blank_article.jpg', upload_to='images/articles/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet,\n    consectetur adipiscing elit. Etiam maximus efficitur lacus, sit amet pretium lorem \n    iaculis id. Nulla hendrerit risus at justo imperdiet, eget sagittis felis consequat. \n    Ut tempor luctus felis id ullamcorper. Ut fringilla pharetra magna a scelerisque.\n    Maecenas nec sem varius mi rhoncus scelerisque sed sed enim. Suspendisse\n    blandit ante at ipsum feugiat, vitae ultrices enim blandit.', max_length=200),
        ),
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet,\n    consectetur adipiscing elit. Etiam maximus efficitur lacus, sit amet pretium lorem \n    iaculis id. Nulla hendrerit risus at justo imperdiet, eget sagittis felis consequat. \n    Ut tempor luctus felis id ullamcorper. Ut fringilla pharetra magna a scelerisque.\n    Maecenas nec sem varius mi rhoncus scelerisque sed sed enim. Suspendisse\n    blandit ante at ipsum feugiat, vitae ultrices enim blandit.', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.ArticleCategory'),
        ),
    ]
