# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171012_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ask',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('NONE', 'None')], default='NONE', max_length=9),
        ),
    ]
