# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_film_ask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='ask',
        ),
    ]
