# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
    ]
