# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_film_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(default='images/none/blank_poster.jpg', upload_to='images/')),
                ('seasons', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
