# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='seasons',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
