# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180117_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
