# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171124_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
