# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('F', 'First Player Wins'), ('S', 'Second Player Wins'), ('D', 'Draw')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='firstapp.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='x',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='move',
            name='y',
            field=models.IntegerField(default=''),
        ),
    ]
