# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20170529_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_to_move',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player',
        ),
        migrations.RemoveField(
            model_name='move',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
