# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serialrating',
            old_name='film',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='serialwatchlist',
            old_name='film',
            new_name='serial',
        ),
    ]
