# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_film_ask'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='book',
            field=models.ManyToManyField(to='api.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='film',
            field=models.ManyToManyField(to='api.Film'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='photos/none/default.png', upload_to='photos/'),
        ),
    ]
