# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171102_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='book',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='film',
        ),
    ]
