# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='photos/none/default.png', upload_to='photos/'),
        ),
    ]
