# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170929_2353'),
        ('user', '0005_auto_20171007_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
        ),
    ]
