# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20171008_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_film',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Film'),
        ),
    ]
