# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20171008_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_film',
        ),
    ]
