# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170929_2353'),
        ('user', '0012_remove_profile_fav_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Film', verbose_name='Film'),
        ),
    ]
