# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_film_image'),
        ('user', '0013_profile_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='film',
        ),
        migrations.AddField(
            model_name='profile',
            name='film',
            field=models.ManyToManyField(blank=True, null=True, to='api.Film', verbose_name='Film'),
        ),
    ]
