# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171012_2052'),
        ('user', '0014_auto_20171012_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='film',
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='api.Book', verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='films',
            field=models.ManyToManyField(to='api.Film'),
        ),
    ]
