# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20171014_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='films',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
