# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20171014_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='films',
        ),
        migrations.AddField(
            model_name='profile',
            name='bread',
            field=models.ManyToManyField(to='user.Bread'),
        ),
    ]
