# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20171014_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bread',
            field=models.ManyToManyField(to='api.Film'),
        ),
    ]
