# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171012_2052'),
        ('user', '0022_auto_20171014_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book',
            field=models.ManyToManyField(to='api.Book'),
        ),
    ]
